spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: paymentService
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/payments/**
        - id: accountService
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/accounts/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 9000
